{% set name = "bluemath-tk" %}
{% set version = "1.1.15" %}
{% set sha256 = "60e643d7a2ccaee46a4c1e24deec333a540c02011ea8f4566d18b53669ee80b0" %}
{% set python_min = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bluemath_tk-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=60
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - numpy
    - pandas
    - xarray
    - netcdf4
    - dask
    - distributed
    - zarr
    - scipy
    - scikit-learn
    - matplotlib-base
    - cartopy
    - jinja2
    - aiohttp
    - minisom
    - statsmodels
    - regionmask
    - cdsapi
    - ecmwf-opendata
    - ipykernel
    - ipywidgets
    - cmocean
    - siphon
    - numba
    - plotly
    - h5py
    - prettytable

test:
  imports:
    - bluemath_tk
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/GeoOcean/BlueMath_tk
  summary: Module collection for custom climate data analysis. The main objective of this Python package is to provide a set of statistical tools tailored for climate data analysis, with a focus on statistical classification and prediction.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tausiaj
